// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// value_map
std::map<int, std::vector<int> > value_map(std::vector<int> x);
RcppExport SEXP _rexmap_value_map(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<int> >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(value_map(x));
    return rcpp_result_gen;
END_RCPP
}
// partid_to_fastqid
std::map<int, std::vector<int> > partid_to_fastqid(std::vector<int> dada_map, std::vector<int> derep_map);
RcppExport SEXP _rexmap_partid_to_fastqid(SEXP dada_mapSEXP, SEXP derep_mapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<int> >::type dada_map(dada_mapSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type derep_map(derep_mapSEXP);
    rcpp_result_gen = Rcpp::wrap(partid_to_fastqid(dada_map, derep_map));
    return rcpp_result_gen;
END_RCPP
}
// consensus_sequence
std::string consensus_sequence(std::vector<std::string> seqs);
RcppExport SEXP _rexmap_consensus_sequence(SEXP seqsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type seqs(seqsSEXP);
    rcpp_result_gen = Rcpp::wrap(consensus_sequence(seqs));
    return rcpp_result_gen;
END_RCPP
}
// hamming
int hamming(std::string s1, std::string s2);
RcppExport SEXP _rexmap_hamming(SEXP s1SEXP, SEXP s2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type s1(s1SEXP);
    Rcpp::traits::input_parameter< std::string >::type s2(s2SEXP);
    rcpp_result_gen = Rcpp::wrap(hamming(s1, s2));
    return rcpp_result_gen;
END_RCPP
}
// compare_alignment
IntegerVector compare_alignment(std::string s1, std::string s2);
RcppExport SEXP _rexmap_compare_alignment(SEXP s1SEXP, SEXP s2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type s1(s1SEXP);
    Rcpp::traits::input_parameter< std::string >::type s2(s2SEXP);
    rcpp_result_gen = Rcpp::wrap(compare_alignment(s1, s2));
    return rcpp_result_gen;
END_RCPP
}
// compare_alignment_ext
IntegerVector compare_alignment_ext(std::string s1, std::string s2);
RcppExport SEXP _rexmap_compare_alignment_ext(SEXP s1SEXP, SEXP s2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type s1(s1SEXP);
    Rcpp::traits::input_parameter< std::string >::type s2(s2SEXP);
    rcpp_result_gen = Rcpp::wrap(compare_alignment_ext(s1, s2));
    return rcpp_result_gen;
END_RCPP
}
// load_posterior
std::vector< std::vector<int> > load_posterior(std::string filename);
RcppExport SEXP _rexmap_load_posterior(SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    rcpp_result_gen = Rcpp::wrap(load_posterior(filename));
    return rcpp_result_gen;
END_RCPP
}
// nwalign_endsfree_test
Rcpp::CharacterVector nwalign_endsfree_test(std::string s1, std::string s2, std::string q1, std::string q2, int match, int mismatch);
RcppExport SEXP _rexmap_nwalign_endsfree_test(SEXP s1SEXP, SEXP s2SEXP, SEXP q1SEXP, SEXP q2SEXP, SEXP matchSEXP, SEXP mismatchSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type s1(s1SEXP);
    Rcpp::traits::input_parameter< std::string >::type s2(s2SEXP);
    Rcpp::traits::input_parameter< std::string >::type q1(q1SEXP);
    Rcpp::traits::input_parameter< std::string >::type q2(q2SEXP);
    Rcpp::traits::input_parameter< int >::type match(matchSEXP);
    Rcpp::traits::input_parameter< int >::type mismatch(mismatchSEXP);
    rcpp_result_gen = Rcpp::wrap(nwalign_endsfree_test(s1, s2, q1, q2, match, mismatch));
    return rcpp_result_gen;
END_RCPP
}
// C_mergepairs
Rcpp::CharacterVector C_mergepairs(std::string s1, std::string s2, std::string q1, std::string q2, std::string posterior_match_file, std::string posterior_mismatch_file, int match, int mismatch, int gap_p, double min_pct_sim, int min_aln_len);
RcppExport SEXP _rexmap_C_mergepairs(SEXP s1SEXP, SEXP s2SEXP, SEXP q1SEXP, SEXP q2SEXP, SEXP posterior_match_fileSEXP, SEXP posterior_mismatch_fileSEXP, SEXP matchSEXP, SEXP mismatchSEXP, SEXP gap_pSEXP, SEXP min_pct_simSEXP, SEXP min_aln_lenSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type s1(s1SEXP);
    Rcpp::traits::input_parameter< std::string >::type s2(s2SEXP);
    Rcpp::traits::input_parameter< std::string >::type q1(q1SEXP);
    Rcpp::traits::input_parameter< std::string >::type q2(q2SEXP);
    Rcpp::traits::input_parameter< std::string >::type posterior_match_file(posterior_match_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type posterior_mismatch_file(posterior_mismatch_fileSEXP);
    Rcpp::traits::input_parameter< int >::type match(matchSEXP);
    Rcpp::traits::input_parameter< int >::type mismatch(mismatchSEXP);
    Rcpp::traits::input_parameter< int >::type gap_p(gap_pSEXP);
    Rcpp::traits::input_parameter< double >::type min_pct_sim(min_pct_simSEXP);
    Rcpp::traits::input_parameter< int >::type min_aln_len(min_aln_lenSEXP);
    rcpp_result_gen = Rcpp::wrap(C_mergepairs(s1, s2, q1, q2, posterior_match_file, posterior_mismatch_file, match, mismatch, gap_p, min_pct_sim, min_aln_len));
    return rcpp_result_gen;
END_RCPP
}
// C_nwalign
Rcpp::CharacterVector C_nwalign(std::string s1, std::string s2, int match, int mismatch, int indel);
RcppExport SEXP _rexmap_C_nwalign(SEXP s1SEXP, SEXP s2SEXP, SEXP matchSEXP, SEXP mismatchSEXP, SEXP indelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type s1(s1SEXP);
    Rcpp::traits::input_parameter< std::string >::type s2(s2SEXP);
    Rcpp::traits::input_parameter< int >::type match(matchSEXP);
    Rcpp::traits::input_parameter< int >::type mismatch(mismatchSEXP);
    Rcpp::traits::input_parameter< int >::type indel(indelSEXP);
    rcpp_result_gen = Rcpp::wrap(C_nwalign(s1, s2, match, mismatch, indel));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rexmap_value_map", (DL_FUNC) &_rexmap_value_map, 1},
    {"_rexmap_partid_to_fastqid", (DL_FUNC) &_rexmap_partid_to_fastqid, 2},
    {"_rexmap_consensus_sequence", (DL_FUNC) &_rexmap_consensus_sequence, 1},
    {"_rexmap_hamming", (DL_FUNC) &_rexmap_hamming, 2},
    {"_rexmap_compare_alignment", (DL_FUNC) &_rexmap_compare_alignment, 2},
    {"_rexmap_compare_alignment_ext", (DL_FUNC) &_rexmap_compare_alignment_ext, 2},
    {"_rexmap_load_posterior", (DL_FUNC) &_rexmap_load_posterior, 1},
    {"_rexmap_nwalign_endsfree_test", (DL_FUNC) &_rexmap_nwalign_endsfree_test, 6},
    {"_rexmap_C_mergepairs", (DL_FUNC) &_rexmap_C_mergepairs, 11},
    {"_rexmap_C_nwalign", (DL_FUNC) &_rexmap_C_nwalign, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_rexmap(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
