# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

value_map <- function(x) {
    .Call('_himap_value_map', PACKAGE = 'himap', x)
}

partid_to_fastqid <- function(dada_map, derep_map) {
    .Call('_himap_partid_to_fastqid', PACKAGE = 'himap', dada_map, derep_map)
}

consensus_sequence <- function(seqs) {
    .Call('_himap_consensus_sequence', PACKAGE = 'himap', seqs)
}

hamming <- function(s1, s2) {
    .Call('_himap_hamming', PACKAGE = 'himap', s1, s2)
}

compare_alignment <- function(s1, s2) {
    .Call('_himap_compare_alignment', PACKAGE = 'himap', s1, s2)
}

load_posterior <- function(filename) {
    .Call('_himap_load_posterior', PACKAGE = 'himap', filename)
}

nwalign_endsfree_test <- function(s1, s2, q1, q2, match = 5L, mismatch = -2L) {
    .Call('_himap_nwalign_endsfree_test', PACKAGE = 'himap', s1, s2, q1, q2, match, mismatch)
}

C_mergepairs <- function(s1, s2, q1, q2, posterior_match_file, posterior_mismatch_file, match, mismatch, gap_p, min_pct_sim, min_aln_len) {
    .Call('_himap_C_mergepairs', PACKAGE = 'himap', s1, s2, q1, q2, posterior_match_file, posterior_mismatch_file, match, mismatch, gap_p, min_pct_sim, min_aln_len)
}

